### ISSUE TITLE
Bug: Restore and Save Cache not working

### ISSUE THREAD

**Issue by jboliveira** [corradin/azure-pipelines-node-modules-caching#2]
## Environment
- Azure Pipelines
- vmImage: 'ubuntu-latest'

## Issue Description

Trying to use/apply the `pipeline caching` concept that was described via [Xebia Blog](https://xebia.com/blog/caching-your-node-modules-in-azure-devops/), but the mechanism doesn't work.
The `Azure Artifact Feed` has been created and configured to have full access via pipelines.
Also applied full access for the user.

### Error logs

```
##[warning]Error: An unexpected error occurred while trying to download the package. Exit code(1) and error({"@t":"2020-02-03T22:35:43.4535538Z","@m":"ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session ","@i":"67e1f99d","SourceContext":"ArtifactTool.Commands.UPackDownloadCommand","UtcTimestamp":"2020-02-03 22:35:43.453Z"}
{"@t":"2020-02-03T22:35:43.9021193Z","@m":"An error occurred on the service. User '' lacks permission to complete this action. You need to have 'ReadPackages'.","@i":"1330842f","@l":"Error","SourceContext":"ArtifactTool.Program","UtcTimestamp":"2020-02-03 22:35:43.902Z"})
##[warning]Issue running universal packages tools
```

**Comment by corradin** [comment]
Hi Jader, currently I am having a flu do I can't do that much. At which task do you get this error?

**Comment by corradin** [comment]
@jboliveira Have you managed to solve this? Maybe you could give me access to your DevOps environment, so I can take a look? Let me know. Cheers!

**Comment by jboliveira** [comment]
@corradin Hey, yes, all good now. Thank you.

**Comment by ybandil** [comment]
@jboliveira, @corradin ,  I am facing the same issue , can you please help me , how should i resolve this?
